version: '3'

services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=appex
      - MYSQL_USER=appex_user
      - MYSQL_PASSWORD=appex_pass
    ports:
      - "3306:3306"
    volumes:
      - appex-mysql-data:/var/lib/mysql
    networks:
      - appex-network

  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    working_dir: /var/www/
    restart: unless-stopped
    volumes:
      - ~/myComp/web-work/local-docker-dev/appex-project/appex:/var/www
    ports:
      - "9000:9000"
      - "5173:5173" # For Vite (vite default port is 5173)
    depends_on:
      - mysql
    networks:
      - appex-network

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ~/myComp/web-work/local-docker-dev/appex-project/appex:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - appex-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - appex-network

volumes:
  appex-mysql-data:


networks:
  appex-network:
