version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - appname-mysql-data:/var/lib/mysql
      - ./docker-compose/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker-compose/mysql/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - appname-network

  app:
    build:
      args:
        appname: ${APP_NAME}
      context: ./
      dockerfile: Dockerfile.dev
    working_dir: /var/www/
    restart: unless-stopped
    volumes:
      - ${PROJECT_PATH}/${APP_NAME}:/var/www
    ports:
      - "9000:9000"
      - "5173:5173" # For Vite (vite default port is 5173)
    depends_on:
      - mysql
    networks:
      - appname-network

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ${PROJECT_PATH}/${APP_NAME}:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - appname-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - appname-network

volumes:
  appname-mysql-data:


networks:
  appname-network:
