version: '3'
services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ${MYSQL_VOLUME_NAME}:/var/lib/mysql
    networks:
      - ${NETWORK_NAME}
      
  app:
    build:
      context: ./
      dockerfile: ${DOCKERFILE_NAME}
    working_dir: ${WORK_DIR}
    restart: unless-stopped
    volumes:
      - ${APP_PATH}:${WORK_DIR}
      - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "${PHP_PORT}:9000"
      - "${VITE_PORT}:5173"
    depends_on:
      - mysql
    networks:
      - ${NETWORK_NAME}
      
  nginx:
    image: nginx:alpine
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - app
    volumes:
      - ${APP_PATH}:${WORK_DIR}
      - ${NGINX_CONFIG_PATH}:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - ${NETWORK_NAME}
      
volumes:
  ${MYSQL_VOLUME_NAME}:
  
networks:
  ${NETWORK_NAME}: