FROM php:8.2-fpm

# Arguments defined in docker-compose.yml
ARG appname

# Install system dependencies, Node.js, Vite, and PHP extensions
RUN apt-get update && apt-get install -y \
    libmemcached-dev \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    libzip-dev \
    mariadb-client \
    npm \
    yarn \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    g++ \
    gcc \
    make \
    autoconf \
    libc-dev \
    pkg-config \
    libssl-dev \
    unixodbc-dev \
    freetds-dev \
    gnupg2 \
    apt-transport-https \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install zip gd mysqli pdo_mysql mbstring exif pcntl bcmath \
    && docker-php-ext-enable gd mysqli \
    && docker-php-ext-install soap \
    && npm install -g vite \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create a new user and set ownership
RUN useradd -m myuser \
    && chown -R myuser:myuser /var/www/

# Set working directory
WORKDIR /var/www/
RUN composer create-project --prefer-dist laravel/laravel ${appname}

# Adjust permissions for Laravel directories within the app directory
RUN chown -R www-data:www-data /var/www/${appname}/storage /var/www/${appname}/bootstrap/cache \
    && chmod -R 775 /var/www/${appname}/storage /var/www/${appname}/bootstrap/cache

# Set the working directory to the Laravel app
WORKDIR /var/www/${appname}